name: System-Dynamics-Textbook
channels:
  - default
dependencies:
  - python=3.7
  - sphinx=2.4.4
  - pip
  - pandas
  - scipy
  - numpy
  - matplotlib
  - plotly
  - notebook
  - pip:
    - quantecon
    - jupyter-book
